name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: node-22

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to Vercel
        run: ./node_modules/.bin/vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
