name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to Vercel
        run: ./node_modules/.bin/vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
